builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Mac
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
gomod:
  proxy: true
  mod: mod
dockers:
  - image_templates: ["fortio/proxy:{{ .Version }}-amd64"]
    use: buildx
    build_flag_templates:
    - --platforms=linux/amd64
  - image_templates: ["fortio/proxy:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates:
    - --platforms=linux/arm64
docker_manifests:
-
  name_template: fortio/proxy:{{ .Version }}
  image_templates:
  - fortio/proxy:{{ .Version }}-amd64
  - fortio/proxy:{{ .Version }}-arm64
